os: osx
language: node_js
node_js:
- '8.12'
branches:
  only:
  - master
before_script:
- openssl aes-256-cbc -K $encrypted_d32b82685a0c_key -iv $encrypted_d32b82685a0c_iv
  -in travis.privatekey.enc -out travis.privatekey -d
- npm install -g firebase-tools
- npm install -g @angular/cli
- brew install git-secret
script:
- gpg --import travis.privatekey
- gpg --import travis.key
- git secret reveal -p $SECRET_PASSWORD
- ng build --prod
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
