#.travis.yml
os: osx

language: node_js
node_js:
  - "8.12"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - brew install gpg
  - brew install git-secret

script:
  - git secret reveal -p $SECRET_PASSWORD
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
