language: node_js
node_js:
- '8.12'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_d32b82685a0c_key -iv $encrypted_d32b82685a0c_iv
  -in travis.privatekey.enc -out travis.privatekey -d
- echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
- wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
- sudo apt-get update && sudo apt-get install git-secret
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
- gpg --list-keys
- gpg --list-secret-keys
script:
- gpg --import travis.key
- echo $SECRET_PASSWORD | gpg --batch --import travis.privatekey
- gpg --list-keys
- gpg --list-secret-keys
- git secret reveal -p $SECRET_PASSWORD -d /home/travis/.gnupg/
- ng build --prod
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change

